# Generated by Django 6.0.7 on 2026-07-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mood_tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='zubora_tag',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
