# Generated by Django 6.0.7 on 2026-08-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
